Websockets & Refactoring
v1-wizard/url_shortener pull request #6
Opened 2018-03-09 10:46 UTC by v1-wizard

- Websocket protocol were added. 
- Error processing were refactored.

2018-03-10 08:42 UTC, Gr1N commented on src/logic.py
> +            'regex': ('http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\(\),]|'
регулярку лучше сразу скомпилировать и положить на уровне модуля, плюс обычно валидация лежит логически отдельно: на уровне view ты валидируешь и потом передаешь в логику. сейчас у тебя намешано

2018-03-10 08:43 UTC, Gr1N commented on src/logic.py
> +        raise web.HTTPBadRequest(reason=v.errors)
какой тут content-type улетает? если отличный от json, то не стоит так делать, с точки зрения клиента обрабатывать будет коряво

2018-03-10 08:45 UTC, Gr1N commented on src/logic.py
> +        'Are you sure?': {
ключи предложениями в пейлоаде? что-то странное, надо стремиться к робоподобным ключам, вдруг ты локализацию захочешь, а тут такое)

2018-03-10 08:46 UTC, Gr1N commented on src/logic.py
> +def purge_all(json_body=None):
а как это вообще работает? передаешь `json_body`, а внизу для валидации используешь `json`

2018-03-10 08:46 UTC, Gr1N commented on src/logic.py
> +def get_all_links(json_body=None):
`json_body` не используется

2018-03-10 08:48 UTC, Gr1N requested changes
🚫

2018-03-10 09:56 UTC, v1-wizard commented on src/logic.py
> +def get_all_links(json_body=None):
Да. Эта штука как и валидация в логике, были сделаны, чтобы переиспользовать код чтобы он работал по http api и по websocket api.

2018-03-10 09:57 UTC, v1-wizard commented on src/logic.py
> +def get_all_links(json_body=None):
Нужен совет, как это можно тогда по другому организовать.

2018-03-10 09:59 UTC, v1-wizard commented on src/logic.py
> +def purge_all(json_body=None):
По видимому оно не работает. =)

2018-03-10 16:56 UTC, v1-wizard commented on src/logic.py
> +        raise web.HTTPBadRequest(reason=v.errors)
`process_error` мидлваря оборачивает это всё в `json_response`.

2018-03-10 18:55 UTC, v1-wizard commented on src/logic.py
> +            'regex': ('http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\(\),]|'
Увы, cerberus не умеет в компиленные regexp. 
> Validation will fail if field value does not match the provided regular expression. It is only tested on string values.
```
cerberus.schema.SchemaError: {'link': [{'regex': ['must be of string type']}]}
```

2018-03-10 19:00 UTC, v1-wizard commented on src/logic.py
> +def purge_all(json_body=None):
Исправил. Спасибо.

2018-03-10 19:00 UTC, v1-wizard commented on src/logic.py
> +        'Are you sure?': {
Исправил. Спасибо

2018-03-11 12:36 UTC, Gr1N commented on src/logic.py
> +            'regex': ('http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\(\),]|'
Вот черти :(

2018-03-11 12:41 UTC, Gr1N commented on src/logic.py
> +            'type': 'string',
А почему тут не использовать просто bool тип и не заморачиваться со строковыми значениями?

2018-03-11 12:41 UTC, Gr1N commented on src/logic.py
> +            'regex': ('http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\(\),]|'
Чертяги

2018-03-11 12:57 UTC, Gr1N commented on src/logic.py
> +def get_all_links(json_body=None):
Понял твою идею, давай немного попробуем причесать.

Я бы попробовал унести все валидационные схемы в отдельный модуль, что-то вроде `schemas.py`, там будут просто словари с описанием твоих входов, сюда бы я его импортировал и использовал схемы как константы. Кажется это упростит этот модуль. 

Дальше надо выбрать, либо остаться с твоим вариантов, когда ты "как бэ" используешь обработчики для HTTP API в WS API, либо пересмотреть этот подход.

Если оставаться с твоим вариантом, я бы подумал над разделением твоего `logic.py` на два, чтобы в одном модуле не обитало все и сразу, возможно что-то вроде `handlers/http.py` и `handlers/ws.py` и это у тебя точно не `logic.py`, это обработчики.

Другой вариант, это упороться и сделать твою логику действительно логикой, это означает, что вся твоя эта логика не нужна вовсе. У тебя уже есть `storage` который за это все отвечает, дальше тебе надо сделать красивые обработчики, которые в каком-то смысле у тебя уже были, но WS доставляет боль. К слову он тебе вообще нужен?

2018-03-11 12:58 UTC, Gr1N commented on src/logic.py
> +        'type': {
обычно такое называю `command`

2018-03-11 13:00 UTC, Gr1N commented on src/main.py
> +def main():
лучше сделать функцию `get_application`, которая у тебя вернет полностью настроенный `web.Application` и что-то вроде:
```
if __name__ == '__main__':
    app = get_application()
    web.run_app(app, port=USH_PORT)
```

Это бывает крайне полезно если потом приложение запускать на каком-нибудь гуникорне например. И в целом это стандартная практика.

2018-03-11 13:01 UTC, Gr1N commented on src/handlers.py
> +            print('Connection closed with exception {}'.format(ws.exception()))
Используй либо стандартный `logging`, либо возьми `structlog`, но не плоди принты.

2018-03-11 13:38 UTC, v1-wizard commented on src/logic.py
> +            'type': 'string',
Я как раз хочу. Чтобы пользователь api заморочился. =)

2018-03-11 14:02 UTC, v1-wizard commented on src/logic.py
> +def get_all_links(json_body=None):
Ну чуваку, который по примеру этого сервиса пишет тесты надо продемонстрировать работу по нескольким протоколам. Так что да.

2018-03-11 14:05 UTC, Gr1N commented on src/logic.py
> +def get_all_links(json_body=None):
Тогда хотя бы схемы и обработчики разнеси.

2018-03-11 14:16 UTC, v1-wizard commented on src/logic.py
> +def get_all_links(json_body=None):
Уберу в `schemas.py`, но возникает вопрос с многопоточностью. Не будет ли к ним конкурентного доступа если `Validator` сделать константой?

2018-03-11 14:20 UTC, v1-wizard commented on src/handlers.py
> +            print('Connection closed with exception {}'.format(ws.exception()))
Рас пошла такая пьянка, то есть примеры того, как лучше инитить стандартный логгер?

2018-03-11 14:29 UTC, Gr1N commented on src/handlers.py
> +            print('Connection closed with exception {}'.format(ws.exception()))
https://docs.python.org/3/howto/logging.html#logging-basic-tutorial
https://docs.python.org/3/howto/logging-cookbook.html#logging-cookbook

👯

2018-03-11 14:32 UTC, Gr1N commented on src/logic.py
> +def get_all_links(json_body=None):
Я предлагал вынести только декларацию схем и делать что-то вроде в обработчиках:
```
v = Validator()
v.validate(document, schema)
```

С многопоточностью тут проблем нету, так как у тебя нету многопоточности :) Но если хочешь валидатор инициализировать на уровне класса, то посмотри как он устроен внутри, все ли будет ок, но скорее всего все будет ок.

2018-03-11 19:02 UTC, Gr1N commented on README.md
> +➜  ~ ws ws://127.0.0.1:8888/ws
было бы круто указать что это за тула `ws` и как это установить

2018-03-11 19:03 UTC, Gr1N commented on src/schemas.py
> +# -*- coding: utf-8 -*-
кодинг не нужен

2018-03-11 19:04 UTC, Gr1N commented on src/schemas.py
> +GET_STATS = {'id': {'type': 'string', 'empty': False, 'required': True}}
сделай все с новой строки, плюс внизу у тебя табуляции поехали

2018-03-11 19:06 UTC, v1-wizard commented on src/schemas.py
> +GET_STATS = {'id': {'type': 'string', 'empty': False, 'required': True}}
Исправлено.

2018-03-11 19:07 UTC, v1-wizard commented on src/schemas.py
> +# -*- coding: utf-8 -*-
Исправлено.

2018-03-11 19:08 UTC, Gr1N commented on src/handlers.py
> +async def redirect(request):
в терминах `aiohttp` все что у тебя тут, есть views, плюс ты сделал новый модуль views :)
может стоит подумать про что-то вроде:
```
views/
    base.py — твои базовые вещи
    api.py — или что-то вроде этого где твой http api
    ws.py — ну и тут понятно
```

2018-03-11 19:12 UTC, v1-wizard commented on README.md
> +➜  ~ ws ws://127.0.0.1:8888/ws
Добавил раздел Links в readme.

2018-03-11 19:13 UTC, v1-wizard commented on src/handlers.py
> +async def redirect(request):
```
handlers/
       base.py
       http.py
       ws.py
``` ??? Только испортить как  from handlers import ... ?

2018-03-11 19:17 UTC, Gr1N commented on src/handlers.py
> +async def redirect(request):
называй лучше view а не хэндлерс, а импортить как захочешь, можно например:
```
import view

views.ws.handler
views.http.shortcut 
...
```
для этого в пакете сделай `__init__.py`, а там:
```
from . import http, ws
```

2018-03-11 19:17 UTC, Gr1N commented on src/handlers.py
> +async def redirect(request):
а вообще как удобнее :)

2018-03-11 20:27 UTC, Gr1N commented on src/storage.py
> +        def generate_lid():
может `uuid.uuid4().hex[:10]`?

2018-03-11 20:28 UTC, v1-wizard commented on src/storage.py
> +        def generate_lid():
Идеально!

2018-03-11 20:29 UTC, Gr1N approved these changes

2018-03-11 20:30 UTC, v1-wizard commented on src/storage.py
> +        def generate_lid():
Исправил.

2018-03-11 20:32 UTC, merged