Storage was changed from TinyDB to Mongo.
v1-wizard/url_shortener pull request #7
Opened 2018-04-17 21:14 UTC by v1-wizard

2018-04-19 07:51 UTC, Gr1N commented on Makefile
> +	@virtualenv -p python3 venv
в свежих питонах можно не использовать отдельный пакет `virtualenv` https://docs.python.org/3/library/venv.html#creating-virtual-environments

2018-04-19 07:52 UTC, Gr1N commented on docker-compose.yml
> +  app:
твой сервис зависит от могли, стоит использовать https://docs.docker.com/compose/compose-file/#depends_on

2018-04-19 07:54 UTC, Gr1N commented on requirements.txt
> +pymongo==3.6.1
по хорошему надо использовать асинхронный драйвер к монге https://github.com/mongodb/motor/

2018-04-19 07:55 UTC, Gr1N requested changes
changes requested

2018-04-19 21:53 UTC, v1-wizard commented on Makefile
> +	@virtualenv -p python3 venv
Исправлено. Спасибо за инфу.

2018-04-19 21:53 UTC, v1-wizard commented on docker-compose.yml
> +  app:
Исправлено.

2018-04-19 21:54 UTC, v1-wizard commented on requirements.txt
> +pymongo==3.6.1
Теперь используется. Спасибо.

2018-04-20 07:20 UTC, Gr1N approved these changes

2018-04-22 09:30 UTC, merged